services:

  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - TZ=Europe/Moscow
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./data/db-dumps:/docker-entrypoint-initdb.d:ro
      - ./data/db:/var/lib/mysql:rw

  pma:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Europe/Moscow

  php-fpm:
    build: ./php
    depends_on:
      - memcached
    links:
      - db
      - memcached
    volumes:
      - ./logs/php:/var/log/php:rw
      - ./php/conf.d/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./php/conf.d/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./php/conf.d/memcached.ini:/usr/local/etc/php/conf.d/xx-php-ext-memcached.ini:ro
      - ./php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini:ro
      - ${APP_PATH}:/var/www/html:rw

  memcached:
    image: memcached:alpine
    volumes:
      - ./logs/memcached:/var/log/memcached
      - ./data/memcached:/var/lib/memcachedcd

  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./logs/nginx:/var/log/nginx:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ${APP_PATH}:/var/www/html:ro
    links:
      - php-fpm:fpm
    environment:
      - TZ=Europe/Moscow
